travis:
  secure:
    BINSTAR_TOKEN: Bm+TF6jrFZ0kI6q6EveHtMsSQloNccV/K4kK/eyiT76V112/8ttBYtu+erLRTTjvxFExdI7j6FuP9vpJkhIIBAtbAVCaiTh8vA/CH1agE6pUSjuRK2tdEniUd6UBQMeWSd7kKwFraMDDmqBkm1z8PVcVKEqWJXDpjuCLviIZWFDFTiI6Wvt9mB9vCaKC5VIbQNX2vJV1aAODbhspjD4ZUgtfmrxcTEK1ubU6YmYwQOvarQx6Ux4fxM9WTur7bUkmfMEul8eTfj3LCaEHHrO+Y8Eadr4WYW4KeVaLbokCMBypyAfDb9bzbVDf8rwDZwveSES6lvswmoD5J+B1F/eG6FTFQVsx9KvbsWKu9rdNAHwRPiMwsleTc24KXbiPt99b9dQZ9jQRnF9t7Wk9uVQGo6dspE2zYAa3yZ8PBe+OZhdIaUkglAguSYmyQL9G/Zglp3ao40Dgi38VJxPINQ0GXzLwFma8aexboHh2FHFsjtI/7K+/Q3JEW9SuKW3Ei9o2mC73CGzCEp4OpZIs8ajABkXhUnyHwkG9MuofDcbIOIESRMl/5IwpNJz2wqvs+nGXR/YH2r9heoxc4D5kOQWedlVenRS3GkzBuOSK+zqWYlUU2jPjjL0XIzrVh0WtIeyPyU+IiKL8ae1+FZYU0MPcQSecwzVR4aVM/MWleowD50Y=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
